feat: delete penis/boob source messages after command
NullDev/CSZ-Bot pull request #296
Opened 2022-12-02 10:20 UTC by fionera

Ungetestet und so aber yolo

2022-12-06 22:16 UTC, twobiers commented
Dann darf der Bot die reply Funktion nicht nutzen, denn sonst löscht er seine Nachricht automatisch.

2022-12-06 22:17 UTC, twobiers requested changes
Wenn die Nachricht gelöscht wird, löscht der bot seine eigene Nachricht auch. Die inline-reply muss gegen eine normale Nachricht ausgetauscht werden

2023-04-09 18:34 UTC, kavejra commented
Die Erwähnung bleibt?

2023-07-05 17:41 UTC, arellak commented
Da hier lange nichts Neues kam, schließe ich die PR erstmal.

2023-07-05 17:41 UTC, closed without merging